<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_gws-output-pages-elements-homepage_addi_575398</name>
   <tag></tag>
   <elementGuidId>9e2a4db6-f14d-4545-9133-76dd87bf05de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gws-output-pages-elements-homepage_additional_languages__als']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gws-output-pages-elements-homepage_additional_languages__als</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d6ea5683-52cb-46a4-b0c4-80f96e845e02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vcVZ7d</value>
      <webElementGuid>9120b82e-378e-434e-bf33-6fc780d922ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gws-output-pages-elements-homepage_additional_languages__als</value>
      <webElementGuid>52c1aa57-97a7-48b3-9e7b-804ccb4848c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>#gws-output-pages-elements-homepage_additional_languages__als{font-size:small;margin-bottom:24px}#SIvCob{color:#4d5156;display:inline-block;line-height:28px;}#SIvCob a{padding:0 3px;}.H6sW5{display:inline-block;margin:0 2px;white-space:nowrap}.z4hgWe{display:inline-block;margin:0 2px}Google offered in:  हिन्दी    বাংলা    తెలుగు    मराठी    தமிழ்    ગુજરાતી    ಕನ್ನಡ    മലയാളം    ਪੰਜਾਬੀ  </value>
      <webElementGuid>be5d306d-316d-4446-8cb9-c1567aaf9c50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gws-output-pages-elements-homepage_additional_languages__als&quot;)</value>
      <webElementGuid>564cb0ae-4c54-4544-adff-81cdd90b1f2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='gws-output-pages-elements-homepage_additional_languages__als']</value>
      <webElementGuid>df13b106-ad66-41e9-b699-c3943cb82454</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div</value>
      <webElementGuid>3ebcce2a-df02-45f4-91c1-7439b3823db9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'gws-output-pages-elements-homepage_additional_languages__als' and (text() = '#gws-output-pages-elements-homepage_additional_languages__als{font-size:small;margin-bottom:24px}#SIvCob{color:#4d5156;display:inline-block;line-height:28px;}#SIvCob a{padding:0 3px;}.H6sW5{display:inline-block;margin:0 2px;white-space:nowrap}.z4hgWe{display:inline-block;margin:0 2px}Google offered in:  हिन्दी    বাংলা    తెలుగు    मराठी    தமிழ்    ગુજરાતી    ಕನ್ನಡ    മലയാളം    ਪੰਜਾਬੀ  ' or . = '#gws-output-pages-elements-homepage_additional_languages__als{font-size:small;margin-bottom:24px}#SIvCob{color:#4d5156;display:inline-block;line-height:28px;}#SIvCob a{padding:0 3px;}.H6sW5{display:inline-block;margin:0 2px;white-space:nowrap}.z4hgWe{display:inline-block;margin:0 2px}Google offered in:  हिन्दी    বাংলা    తెలుగు    मराठी    தமிழ்    ગુજરાતી    ಕನ್ನಡ    മലയാളം    ਪੰਜਾਬੀ  ')]</value>
      <webElementGuid>ecaeefb6-a4ec-419b-8f15-4bb672643298</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
